2019-12-18 23:47:57,880 - ShiftBotLog
	ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/yusuk/rabhare6it/ShiftBot4LabSlack/plugins/Repository.py", line 195, in presentMinutes
    pres = result[0]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yusuk/rabhare6it/ShiftBot4LabSlack/plugins/Service.py", line 98, in sendMinutesTaker
    name = repo.presentMinutes("b4")
  File "/Users/yusuk/rabhare6it/ShiftBot4LabSlack/plugins/Repository.py", line 202, in presentMinutes
    pres = result[0]
TypeError: 'NoneType' object is not subscriptable
